---
language: python
python: "2.7"

env:
  - SITE=test.yml

install:
  - pip install ansible
  - ansible-galaxy install futurice.sentry --roles-path=../ --ignore-errors
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local"
